package evidence

import (
	"fmt"
	"html/template"
	"os"
)

type ScreenshotGuide struct {
	ControlID  string
	Service    string
	Steps      []Step
	ConsoleURL string
	Highlights []Rectangle
}

type Step struct {
	Number      int
	Instruction string
	Screenshot  string
}

type Rectangle struct {
	X      int
	Y      int
	Width  int
	Height int
}

func GenerateHTMLGuide(controlID string, outputPath string) error {
	guides := getGuides()
	guide, exists := guides[controlID]
	if !exists {
		return fmt.Errorf("no guide for control %s", controlID)
	}

	tmpl := `<!DOCTYPE html>
<html>
<head>
    <title>Evidence Collection Guide - {{.ControlID}}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 40px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            max-width: 900px;
            margin: 0 auto;
        }
        h1 {
            color: #0366d6;
            border-bottom: 2px solid #e1e4e8;
            padding-bottom: 10px;
        }
        .step {
            margin: 20px 0;
            padding: 20px;
            background: #f6f8fa;
            border-left: 4px solid #0366d6;
            border-radius: 4px;
        }
        .step-number {
            font-size: 24px;
            font-weight: bold;
            color: #0366d6;
            margin-bottom: 10px;
        }
        .highlight-box {
            border: 3px solid #dc3545;
            background: rgba(220, 53, 69, 0.1);
            padding: 10px;
            margin: 10px 0;
            border-radius: 4px;
        }
        .console-link {
            display: inline-block;
            padding: 12px 24px;
            background: #0366d6;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            font-weight: bold;
            margin: 20px 0;
        }
        .console-link:hover {
            background: #0256c7;
        }
        .warning {
            background: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 4px;
            margin: 20px 0;
        }
        .screenshot-area {
            border: 2px dashed #dc3545;
            padding: 20px;
            text-align: center;
            background: #fff;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1> Screenshot Guide: {{.ControlID}} - {{.Service}}</h1>
        
        <div class="warning">
            <strong> Important:</strong> Auditors need specific screenshots as evidence. Follow each step exactly and capture the highlighted areas.
        </div>
        
        <a href="{{.ConsoleURL}}" target="_blank" class="console-link">Open AWS Console →</a>
        
        {{range .Steps}}
        <div class="step">
            <div class="step-number">Step {{.Number}}</div>
            <p>{{.Instruction}}</p>
            {{if .Screenshot}}
            <div class="screenshot-area">
                <p>📷 Take screenshot here showing: <strong>{{.Screenshot}}</strong></p>
            </div>
            {{end}}
        </div>
        {{end}}
        
        <div class="highlight-box">
            <h3>What auditors look for:</h3>
            <ul>
                <li>Timestamp visible in screenshot</li>
                <li>Account ID or identifier visible</li>
                <li>Setting status clearly shown</li>
                <li>No sensitive data exposed</li>
            </ul>
        </div>
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #586069; font-size: 12px;">
            Generated by AuditKit | <a href="https://github.com/guardian-nexus/AuditKit-Community-Edition">GitHub</a>
        </div>
    </div>
</body>
</html>`

	t, err := template.New("guide").Parse(tmpl)
	if err != nil {
		return err
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	return t.Execute(file, guide)
}

func getGuides() map[string]ScreenshotGuide {
	return map[string]ScreenshotGuide{
		"CC6.6": {
			ControlID:  "CC6.6",
			Service:    "IAM - Root MFA",
			ConsoleURL: "https://console.aws.amazon.com/iam/home#/security_credentials",
			Steps: []Step{
				{
					Number:      1,
					Instruction: "Sign in to AWS Console as the root user (use your root email, not IAM user)",
					Screenshot:  "",
				},
				{
					Number:      2,
					Instruction: "Click on your account name in top-right corner",
					Screenshot:  "",
				},
				{
					Number:      3,
					Instruction: "Select 'Security credentials' from the dropdown",
					Screenshot:  "",
				},
				{
					Number:      4,
					Instruction: "Find the 'Multi-factor authentication (MFA)' section",
					Screenshot:  "The entire MFA section showing 'MFA devices' with status",
				},
				{
					Number:      5,
					Instruction: "Screenshot must clearly show at least one MFA device assigned with 'Active' status",
					Screenshot:  "Device name, type, and identifier visible",
				},
			},
		},
		"CC6.2": {
			ControlID:  "CC6.2",
			Service:    "S3 - Public Access",
			ConsoleURL: "https://s3.console.aws.amazon.com/s3/buckets",
			Steps: []Step{
				{
					Number:      1,
					Instruction: "Open S3 Console and click on the bucket name",
					Screenshot:  "",
				},
				{
					Number:      2,
					Instruction: "Click the 'Permissions' tab",
					Screenshot:  "",
				},
				{
					Number:      3,
					Instruction: "Scroll to 'Block public access (bucket settings)' section",
					Screenshot:  "All 4 settings showing 'On' status",
				},
				{
					Number:      4,
					Instruction: "Ensure all four options are enabled: Block all public access",
					Screenshot:  "The edit button and all toggles clearly visible",
				},
			},
		},
	}
}
